blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/semicolon-devteam/docs/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ 
  - name: ğŸ“š Documentation
    url: https://semicolon-devteam.github.io/docs
    about: ë¬¸ì„œë¥¼ ë¨¼ì € í™•ì¸í•˜ì„¸ìš”
  - name: ğŸ’¬ Slack
    url: https://semicolon-team.slack.com
    about: ì‹¤ì‹œê°„ ë„ì›€ì´ í•„ìš”í•œ ê²½ìš°